# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:/+VuSPikYzoRCbjdjcpCNOeJjTUKzt9q31q1v5wFp5cGw2GP90qUZsjqiiJiD9Xo,iv:RlLih/mM7+WoL0AwbMAXpmx1aKCqjHuETyrQl81j0Jk=,tag:o5avQ0/4ueXfGs+gluOZqg==,type:str]
    POSTGRESQL: ENC[AES256_GCM,data:9pPMnoB8HJvG7KrKr1lrwJmRVzCLasQu4kgGq/U9AsAwzdADraZZqR8C/ua98Ftp,iv:BNoiPWqONHSm74FFQOgqG9rgja5Sc/f24BMrmMJxgpM=,tag:ldP41rFkM4vLZn5MbUoL4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sdgrrkhldwdv7c0y02drn8yalyv3ta65klra8ka6c4xdjt8x8uqqjlcnvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNzROODVveUJrYnBPQ1Rp
            TWpXQjBsSFZkK1RVYlRyYUJFN29Pc2JIeEFZCnIyaGc0TExKeDhPS0Zzb2VGR3lU
            M1oxUUlQbDR0NktkLzRvTjFPdGxpTkkKLS0tIHg0RjZERUhBQnJXYWpWeWY4aUdp
            MWwrdkQ0VDNkZFF4c01GZGJHUlNtYjAKu99T76mla82Ct99F5NaYDqr10AkS98WS
            IWypVL3SiukT4Lt99ujLwhKyRUHeAjRSZ/Hds6s7BPuRAjeiavK1AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-20T16:55:55Z"
    mac: ENC[AES256_GCM,data:8cpJoMZndjVnm5+Cu8vuvF9xPt+L76t5RxhFjNiFgNJOS1hxfLuae3pRABT+X7s+tsZwU2oUyAo5rwkwYWK6BouTKDdXq4rRMIo3n9HPPn7kK9GJuJea7Opx9xkmNYMGIsy/SRB5pJ+QAbyEPSDARMO0Zt4Fe28totPSxHeDSeg=,iv:g06FOxZOK+kGCW+ALZwNA1LKtLMl6UDbYyStKTXtVeI=,tag:C3mjCy5TFel9qLmbFtqSnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
