---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2022.3.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: "${SECRET_KEY}"
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.beryju.org, and is fully opt-in
      error_reporting:
        enabled: false
      postgresql:
        password: "${POSTGRESQL}"

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
      - host: authentik.${SECRET_DOMAIN}
        paths:
        - path: "/"
          pathType: Prefix
      tls:
        - hosts:
            - "authentik.${SECRET_DOMAIN}"
          secretName: "authentik-tls"

    postgresql:
      enabled: true
      postgresqlPassword: "${POSTGRESQL}"
    redis:
      enabled: true
