---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2022.3.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: "eqHS7UUkF/qKh4P14F/C/ZwSlRZiWoJ1yrdT0PRWSfN3vVIa"
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.beryju.org, and is fully opt-in
      error_reporting:
        enabled: true
      postgresql:
        password: "eqHS7UUkF/qKh4P14F/C/ZwSlRZiWoJ1yrdT0PRWSfN3vVIa"

    ingress:
      enabled: true
      hosts:
      - host: authentik.${SECRET_DOMAIN}
        paths:
        - path: "/"
          pathType: Prefix

    postgresql:
      enabled: true
      postgresqlPassword: "eqHS7UUkF/qKh4P14F/C/ZwSlRZiWoJ1yrdT0PRWSfN3vVIa"
    redis:
      enabled: true
